// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutErrors, AuthLogoutResponses, AuthRefreshData, AuthRefreshErrors, AuthRefreshResponses, ConfirmInstanceUploadData, ConfirmInstanceUploadErrors, ConfirmInstanceUploadResponses, CreateInstanceData, CreateInstanceDownloadUrlData, CreateInstanceDownloadUrlErrors, CreateInstanceDownloadUrlResponses, CreateInstanceErrors, CreateInstanceResponses, CreateInstanceUploadUrlData, CreateInstanceUploadUrlErrors, CreateInstanceUploadUrlResponses, DeleteInstanceData, DeleteInstanceErrors, DeleteInstanceResponses, GetInstanceData, GetInstanceErrors, GetInstanceResponses, GetMeData, GetMeErrors, GetMeResponses, GetMinecraftAccountData, GetMinecraftAccountErrors, GetMinecraftAccountResponses, GetMinecraftAccountsData, GetMinecraftAccountsErrors, GetMinecraftAccountsResponses, GetSettingsData, GetSettingsErrors, GetSettingsResponses, ListInstancesData, ListInstancesErrors, ListInstancesResponses, MinecraftLinkCallbackData, MinecraftLinkCallbackErrors, MinecraftLinkCallbackResponses, MinecraftLinkData, MinecraftLinkErrors, MinecraftLinkResponses, MinecraftRefreshTokenData, MinecraftRefreshTokenErrors, MinecraftRefreshTokenResponses, PutSettingsData, PutSettingsErrors, PutSettingsResponses, UnlinkMinecraftAccountData, UnlinkMinecraftAccountErrors, UnlinkMinecraftAccountResponses, UpdateInstanceData, UpdateInstanceErrors, UpdateInstanceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Log out the current device
 *
 * Deletes the session associated with the given refresh token. The access token remains valid until it expires, but the refresh token can no longer be used.
 */
export const authLogout = <ThrowOnError extends boolean = false>(options: Options<AuthLogoutData, ThrowOnError>): RequestResult<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError> => (options.client ?? client).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({
    url: '/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Exchange a refresh token for a new access/refresh token pair
 *
 * Refresh tokens are rotated on every use: the old one is invalidated and a new one is returned. If this call fails with 401, the user must log in again.
 */
export const authRefresh = <ThrowOnError extends boolean = false>(options: Options<AuthRefreshData, ThrowOnError>): RequestResult<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError> => (options.client ?? client).post<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start OAuth login
 *
 * Redirects the user's browser to begin the login flow.
 */
export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> => (options.client ?? client).get<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({ url: '/auth/{provider}/login', ...options });

/**
 * List (or sync) the user's instances
 */
export const listInstances = <ThrowOnError extends boolean = false>(options?: Options<ListInstancesData, ThrowOnError>): RequestResult<ListInstancesResponses, ListInstancesErrors, ThrowOnError> => (options?.client ?? client).get<ListInstancesResponses, ListInstancesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances',
    ...options
});

/**
 * Create a new instance
 */
export const createInstance = <ThrowOnError extends boolean = false>(options: Options<CreateInstanceData, ThrowOnError>): RequestResult<CreateInstanceResponses, CreateInstanceErrors, ThrowOnError> => (options.client ?? client).post<CreateInstanceResponses, CreateInstanceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an instance (and its uploaded archive, if any)
 */
export const deleteInstance = <ThrowOnError extends boolean = false>(options: Options<DeleteInstanceData, ThrowOnError>): RequestResult<DeleteInstanceResponses, DeleteInstanceErrors, ThrowOnError> => (options.client ?? client).delete<DeleteInstanceResponses, DeleteInstanceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}',
    ...options
});

/**
 * Get a single instance
 */
export const getInstance = <ThrowOnError extends boolean = false>(options: Options<GetInstanceData, ThrowOnError>): RequestResult<GetInstanceResponses, GetInstanceErrors, ThrowOnError> => (options.client ?? client).get<GetInstanceResponses, GetInstanceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}',
    ...options
});

/**
 * Replace an instance's metadata/config
 */
export const updateInstance = <ThrowOnError extends boolean = false>(options: Options<UpdateInstanceData, ThrowOnError>): RequestResult<UpdateInstanceResponses, UpdateInstanceErrors, ThrowOnError> => (options.client ?? client).put<UpdateInstanceResponses, UpdateInstanceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Mark the instance's packaged archive as uploaded
 */
export const confirmInstanceUpload = <ThrowOnError extends boolean = false>(options: Options<ConfirmInstanceUploadData, ThrowOnError>): RequestResult<ConfirmInstanceUploadResponses, ConfirmInstanceUploadErrors, ThrowOnError> => (options.client ?? client).post<ConfirmInstanceUploadResponses, ConfirmInstanceUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}/confirm-upload',
    ...options
});

/**
 * Get a presigned URL to download the instance's packaged files
 */
export const createInstanceDownloadUrl = <ThrowOnError extends boolean = false>(options: Options<CreateInstanceDownloadUrlData, ThrowOnError>): RequestResult<CreateInstanceDownloadUrlResponses, CreateInstanceDownloadUrlErrors, ThrowOnError> => (options.client ?? client).get<CreateInstanceDownloadUrlResponses, CreateInstanceDownloadUrlErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}/download-url',
    ...options
});

/**
 * Get a presigned URL to upload the instance's packaged files
 *
 * PUT the instance archive directly to this URL (e.g. with curl -T or reqwest), then call POST /instances/{id}/confirm-upload.
 */
export const createInstanceUploadUrl = <ThrowOnError extends boolean = false>(options: Options<CreateInstanceUploadUrlData, ThrowOnError>): RequestResult<CreateInstanceUploadUrlResponses, CreateInstanceUploadUrlErrors, ThrowOnError> => (options.client ?? client).post<CreateInstanceUploadUrlResponses, CreateInstanceUploadUrlErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}/upload-url',
    ...options
});

/**
 * Get the current user's profile
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me',
    ...options
});

/**
 * Unlink minecraft account
 *
 * Unlinks minecraft account from the current user
 */
export const unlinkMinecraftAccount = <ThrowOnError extends boolean = false>(options: Options<UnlinkMinecraftAccountData, ThrowOnError>): RequestResult<UnlinkMinecraftAccountResponses, UnlinkMinecraftAccountErrors, ThrowOnError> => (options.client ?? client).delete<UnlinkMinecraftAccountResponses, UnlinkMinecraftAccountErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/minecraft/account',
    ...options
});

/**
 * Get minecraft account
 *
 * Returns a minecraft account linked to the current user
 */
export const getMinecraftAccount = <ThrowOnError extends boolean = false>(options: Options<GetMinecraftAccountData, ThrowOnError>): RequestResult<GetMinecraftAccountResponses, GetMinecraftAccountErrors, ThrowOnError> => (options.client ?? client).get<GetMinecraftAccountResponses, GetMinecraftAccountErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/minecraft/account',
    ...options
});

/**
 * Link minecraft account
 *
 * Links minecraft account to current user using microsoft oauth
 */
export const minecraftLink = <ThrowOnError extends boolean = false>(options?: Options<MinecraftLinkData, ThrowOnError>): RequestResult<MinecraftLinkResponses, MinecraftLinkErrors, ThrowOnError> => (options?.client ?? client).post<MinecraftLinkResponses, MinecraftLinkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/minecraft/account/link',
    ...options
});

/**
 * Refresh minecraft access token
 *
 * Refreshes the minecraft access token for the current user
 */
export const minecraftRefreshToken = <ThrowOnError extends boolean = false>(options: Options<MinecraftRefreshTokenData, ThrowOnError>): RequestResult<MinecraftRefreshTokenResponses, MinecraftRefreshTokenErrors, ThrowOnError> => (options.client ?? client).get<MinecraftRefreshTokenResponses, MinecraftRefreshTokenErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/minecraft/account/refresh',
    ...options
});

/**
 * Get minecraft accounts
 *
 * Returns a list of minecraft accounts linked to the current user
 */
export const getMinecraftAccounts = <ThrowOnError extends boolean = false>(options?: Options<GetMinecraftAccountsData, ThrowOnError>): RequestResult<GetMinecraftAccountsResponses, GetMinecraftAccountsErrors, ThrowOnError> => (options?.client ?? client).get<GetMinecraftAccountsResponses, GetMinecraftAccountsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/minecraft/accounts',
    ...options
});

/**
 * Minecraft link callback
 *
 * Handles redirect from microsoft to obrain tokens
 */
export const minecraftLinkCallback = <ThrowOnError extends boolean = false>(options?: Options<MinecraftLinkCallbackData, ThrowOnError>): RequestResult<MinecraftLinkCallbackResponses, MinecraftLinkCallbackErrors, ThrowOnError> => (options?.client ?? client).get<MinecraftLinkCallbackResponses, MinecraftLinkCallbackErrors, ThrowOnError>({ url: '/minecraft/link/callback', ...options });

/**
 * Get the current user's synced settings
 *
 * Returns 404 if the user has never saved settings; the launcher should fall back to its local defaults in that case.
 */
export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>): RequestResult<GetSettingsResponses, GetSettingsErrors, ThrowOnError> => (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings',
    ...options
});

/**
 * Replace the current user's synced settings
 *
 * This is a full replace, not a merge - the launcher should send its complete settings object.
 */
export const putSettings = <ThrowOnError extends boolean = false>(options: Options<PutSettingsData, ThrowOnError>): RequestResult<PutSettingsResponses, PutSettingsErrors, ThrowOnError> => (options.client ?? client).put<PutSettingsResponses, PutSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
