/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`auth_login`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthLoginError {
    DefaultResponse(models::ErrorModel),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`auth_logout`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthLogoutError {
    DefaultResponse(models::ErrorModel),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`auth_refresh`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthRefreshError {
    DefaultResponse(models::ErrorModel),
    UnknownValue(serde_json::Value),
}


/// Redirects the user's browser to Google or Microsoft to begin the login flow.
pub async fn auth_login(configuration: &configuration::Configuration, provider: &str, caller: Option<&str>) -> Result<(), Error<AuthLoginError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_provider = provider;
    let p_query_caller = caller;

    let uri_str = format!("{}/auth/{provider}/login", configuration.base_path, provider=crate::apis::urlencode(p_path_provider));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_caller {
        req_builder = req_builder.query(&[("caller", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthLoginError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Deletes the session associated with the given refresh token. The access token remains valid until it expires, but the refresh token can no longer be used.
pub async fn auth_logout(configuration: &configuration::Configuration, logout_input_body: models::LogoutInputBody) -> Result<models::LogoutOutputBody, Error<AuthLogoutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_logout_input_body = logout_input_body;

    let uri_str = format!("{}/auth/logout", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_logout_input_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LogoutOutputBody`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LogoutOutputBody`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthLogoutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Refresh tokens are rotated on every use: the old one is invalidated and a new one is returned. If this call fails with 401, the user must log in again.
pub async fn auth_refresh(configuration: &configuration::Configuration, refresh_input_body: models::RefreshInputBody) -> Result<models::TokenPair, Error<AuthRefreshError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_refresh_input_body = refresh_input_body;

    let uri_str = format!("{}/auth/refresh", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_refresh_input_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TokenPair`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TokenPair`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthRefreshError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

