/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`minecraft_link_callback`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MinecraftLinkCallbackError {
    DefaultResponse(models::ErrorModel),
    UnknownValue(serde_json::Value),
}


/// Handles redirect from microsoft to obrain tokens
pub async fn minecraft_link_callback(configuration: &configuration::Configuration, code: Option<&str>, state: Option<&str>, error: Option<&str>) -> Result<(), Error<MinecraftLinkCallbackError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_code = code;
    let p_query_state = state;
    let p_query_error = error;

    let uri_str = format!("{}/minecraft/link/callback", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_code {
        req_builder = req_builder.query(&[("code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_state {
        req_builder = req_builder.query(&[("state", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_error {
        req_builder = req_builder.query(&[("error", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<MinecraftLinkCallbackError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

