/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceResponse {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    #[serde(rename = "config", deserialize_with = "Option::deserialize")]
    pub config: Option<serde_json::Value>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Whether a packaged archive exists in object storage for this instance
    #[serde(rename = "has_upload")]
    pub has_upload: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "mc_version")]
    pub mc_version: String,
    #[serde(rename = "mod_loader")]
    pub mod_loader: String,
    #[serde(rename = "mod_loader_version")]
    pub mod_loader_version: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl InstanceResponse {
    pub fn new(config: Option<serde_json::Value>, created_at: chrono::DateTime<chrono::FixedOffset>, has_upload: bool, id: String, mc_version: String, mod_loader: String, mod_loader_version: String, name: String, updated_at: chrono::DateTime<chrono::FixedOffset>) -> InstanceResponse {
        InstanceResponse {
            dollar_schema: None,
            config,
            created_at,
            has_upload,
            id,
            mc_version,
            mod_loader,
            mod_loader_version,
            name,
            updated_at,
        }
    }
}

