/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceBody {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    #[serde(rename = "config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config: Option<Option<serde_json::Value>>,
    /// Minecraft version, e.g. '1.20.1'
    #[serde(rename = "mc_version")]
    pub mc_version: String,
    #[serde(rename = "mod_loader", skip_serializing_if = "Option::is_none")]
    pub mod_loader: Option<ModLoader>,
    /// Loader version, empty for vanilla
    #[serde(rename = "mod_loader_version", skip_serializing_if = "Option::is_none")]
    pub mod_loader_version: Option<String>,
    /// Display name shown in the launcher
    #[serde(rename = "name")]
    pub name: String,
}

impl InstanceBody {
    pub fn new(mc_version: String, name: String) -> InstanceBody {
        InstanceBody {
            dollar_schema: None,
            config: None,
            mc_version,
            mod_loader: None,
            mod_loader_version: None,
            name,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModLoader {
    #[serde(rename = "forge")]
    Forge,
    #[serde(rename = "neoforge")]
    Neoforge,
    #[serde(rename = "fabric")]
    Fabric,
    #[serde(rename = "quilt")]
    Quilt,
}

impl Default for ModLoader {
    fn default() -> ModLoader {
        Self::Forge
    }
}

