/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOutputBody {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    #[serde(rename = "instances", deserialize_with = "Option::deserialize")]
    pub instances: Option<Vec<models::InstanceResponse>>,
    /// Current server time - store this and pass it as 'since' on the next sync
    #[serde(rename = "server_now")]
    pub server_now: chrono::DateTime<chrono::FixedOffset>,
}

impl ListOutputBody {
    pub fn new(instances: Option<Vec<models::InstanceResponse>>, server_now: chrono::DateTime<chrono::FixedOffset>) -> ListOutputBody {
        ListOutputBody {
            dollar_schema: None,
            instances,
            server_now,
        }
    }
}

