/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogoutInputBody {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    /// The refresh token of the session (device) to log out
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
}

impl LogoutInputBody {
    pub fn new(refresh_token: String) -> LogoutInputBody {
        LogoutInputBody {
            dollar_schema: None,
            refresh_token,
        }
    }
}

