/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinecraftAccount {
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "minecraft_uuid")]
    pub minecraft_uuid: String,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl MinecraftAccount {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, id: String, minecraft_uuid: String, updated_at: chrono::DateTime<chrono::FixedOffset>, user_id: String, username: String) -> MinecraftAccount {
        MinecraftAccount {
            created_at,
            id,
            minecraft_uuid,
            updated_at,
            user_id,
            username,
        }
    }
}

