/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresignOutputBody {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    #[serde(rename = "expires_at")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "url")]
    pub url: String,
}

impl PresignOutputBody {
    pub fn new(expires_at: chrono::DateTime<chrono::FixedOffset>, url: String) -> PresignOutputBody {
        PresignOutputBody {
            dollar_schema: None,
            expires_at,
            url,
        }
    }
}

