/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenPair {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    /// Short-lived JWT, send as 'Authorization: Bearer <token>'
    #[serde(rename = "access_token")]
    pub access_token: String,
    /// Access token lifetime in seconds
    #[serde(rename = "expires_in")]
    pub expires_in: i64,
    /// Long-lived opaque token, used to obtain new access tokens
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
}

impl TokenPair {
    pub fn new(access_token: String, expires_in: i64, refresh_token: String) -> TokenPair {
        TokenPair {
            dollar_schema: None,
            access_token,
            expires_in,
            refresh_token,
        }
    }
}

