/*
 * POTN Launcher API
 *
 * Backend API for the POTN Minecraft launcher: authentication, instance sync, and settings sync.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// A URL to the JSON Schema for this object.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub dollar_schema: Option<String>,
    #[serde(rename = "avatar_url", skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl User {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, display_name: String, email: String, id: String, updated_at: chrono::DateTime<chrono::FixedOffset>) -> User {
        User {
            dollar_schema: None,
            avatar_url: None,
            created_at,
            display_name,
            email,
            id,
            updated_at,
        }
    }
}

